Certainly, we can generate a list of filenames for each dataset family based on the conventions and details you've provided. Below, I will create separate lists for each family of datasets, iterating over the necessary parameters like years, fractions, and base strings.

### 1. Datasets Procesados - Estadísticas Descriptivas

Stored in 'results_path'.

Format: `result_[base_str]_Q-[grouper]_[FRAC].csv`

For example: `result_H_Q-Total_pais_0.005.csv`

### 2. Base de Datos: Pobreza para Hogares por Año y Trimestre

- Personas Ingresos Format: `personas_ingresos_f[FRAC]_[Q]_[EXPERIMENT_TAG].csv`
- Pobreza Hogares Format: `pobreza_hogares_f[FRAC]_q[Q]_[EXPERIMENT_TAG].csv`
- Hogares Geo Format: `hogares_geo_f[FRAC]_[YEAR]_[EXPERIMENT_TAG].csv`

### 3. Pobreza en Argentina - Datos GeoJSON por Niveles Geográficos

Format: `[METHOD]_[GEO_LEVEL].geojson`

Where:
- `[METHOD]` includes H, M14, M24, P
- `[GEO_LEVEL]` includes DPTO, IDFRAC, PROV

Let's proceed to generate the file names lists.

Here are the generated lists of filenames based on the conventions you provided:

In [2]:
fracs = [0.01, 0.02]

In [3]:
import pandas as pd

# 1. Datasets Procesados - Estadísticas Descriptivas
results_base_strs = ['H', 'M14', 'M24', 'P']
groupersP = [ # ['Q', 'distrito_id',	'seccion_id', 'seccion_nombre', 'circuito'], 
    ['Q','Total'], ['Q','AGLOSI'], ['Q','AGLOMERADO'], ['Q','Region'], ['Q','PROV'], ['Q','DPTO'], ['Q','P0910'], 
             ['Q','Region', 'AGLOSI'], ['Q', 'PROV', 'AGLOSI']]

groupersH = [['Q','Total'], ['Q','AGLOSI'], ['Q','AGLOMERADO'], ['Q','Region'], ['Q','PROV'], ['Q','DPTO'],
            #  ]#,
             ['Q','Region', 'AGLOSI'], ['Q', 'PROV', 'AGLOSI']]

groupers = groupersP + groupersH
results_groupers = set(tuple(item) for item in groupers)
results_groupers = [list(item) for item in results_groupers]


results_fracs = [0.02]
results_filenames = [
    f"stats_{base_str}_{'-'.join(grouper)}_sample{frac}.csv"
    for base_str in results_base_strs 
    for grouper in results_groupers 
    for frac in results_fracs
]

# 2. Base de Datos: Pobreza para Hogares por Año y Trimestre
pobreza_fracs = fracs
pobreza_years = range(2020, 2025)  # Assuming data from 2018 to 2022
pobreza_quarters = [f"{year}-{d}" for year in pobreza_years for d in ['02-15', '05-15', '08-15', '11-15']]
pobreza_experiment_tags = ['ARG']

personas_ingresos_filenames = [
    f"individual_income_sample{frac}_q{quarter}_{tag}.csv"
    for frac in pobreza_fracs
    for quarter in pobreza_quarters
    for tag in pobreza_experiment_tags
]

pobreza_hogares_filenames = [
    f"household_poverty_sample{frac}_q{quarter}_{tag}.csv"
    for frac in pobreza_fracs
    for quarter in pobreza_quarters
    for tag in pobreza_experiment_tags
]

hogares_geo_filenames = [
    f"geo_households_sample{frac}_{year}_{tag}.csv"
    for frac in pobreza_fracs
    for year in pobreza_years
    for tag in pobreza_experiment_tags
]

# 3. Pobreza en Argentina - Datos GeoJSON por Niveles Geográficos
methods = ['H', 'M14', 'M24', 'P']
geo_levels = ['DPTO', 'IDFRAC', 'PROV']
geojson_filenames = [f"pobreza_{method}_{geo_level}_sample{frac}.geojson" for method in methods for geo_level in geo_levels for frac in pobreza_fracs]




# Paths for each family of datasets
results_path = './../data/results/'
pobreza_path = './../data/Pobreza/'
geojson_path = './../data/geojson/'

# Update file paths
results_filenames = [f"{filename}" for filename in results_filenames]
personas_ingresos_filenames = [f"{filename}" for filename in personas_ingresos_filenames]
pobreza_hogares_filenames = [f"{filename}" for filename in pobreza_hogares_filenames]
hogares_geo_filenames = [f"{filename}" for filename in hogares_geo_filenames]
geojson_filenames = [f"{filename}" for filename in geojson_filenames]

# Display the first filename from each list to check the update
for file_list in [results_filenames, personas_ingresos_filenames, pobreza_hogares_filenames, hogares_geo_filenames, geojson_filenames]:
    print(file_list[0])



# # Display the generated filenames
# results_filenames, personas_ingresos_filenames, pobreza_hogares_filenames, hogares_geo_filenames, geojson_filenames

stats_H_Q-Region_sample0.02.csv
individual_income_sample0.01_2020-02-15_ARG.csv
household_poverty_sample0.01_q2020-02-15_ARG.csv
geo_households_sample0.01_2020_ARG.csv
pobreza_H_DPTO_sample0.01.geojson

In [4]:
results_df = pd.DataFrame({
    'base_str': [base_str for base_str in results_base_strs for _ in results_groupers for _ in results_fracs],
    'grouper': [grouper for _ in results_base_strs for grouper in results_groupers for _ in results_fracs],
    'frac': [frac for _ in results_base_strs for _ in results_groupers for frac in results_fracs],
    'filename': results_filenames,
    'full_path': [f"{results_path}{filename}" for filename in results_filenames]
})

In [5]:
results_df['grouper'] = results_df['grouper'].astype(str)

In [6]:
results_df.loc[results_df.frac == 0.02].set_index(['grouper', 'base_str'])['filename'].unstack()

base_str,H,M14,M24,P
grouper,,,,
"['Q', 'AGLOMERADO']",stats_H_Q-AGLOMERADO_sample0.02.csv,stats_M14_Q-AGLOMERADO_sample0.02.csv,stats_M24_Q-AGLOMERADO_sample0.02.csv,stats_P_Q-AGLOMERADO_sample0.02.csv
"['Q', 'AGLOSI']",stats_H_Q-AGLOSI_sample0.02.csv,stats_M14_Q-AGLOSI_sample0.02.csv,stats_M24_Q-AGLOSI_sample0.02.csv,stats_P_Q-AGLOSI_sample0.02.csv
"['Q', 'DPTO']",stats_H_Q-DPTO_sample0.02.csv,stats_M14_Q-DPTO_sample0.02.csv,stats_M24_Q-DPTO_sample0.02.csv,stats_P_Q-DPTO_sample0.02.csv
"['Q', 'P0910']",stats_H_Q-P0910_sample0.02.csv,stats_M14_Q-P0910_sample0.02.csv,stats_M24_Q-P0910_sample0.02.csv,stats_P_Q-P0910_sample0.02.csv
"['Q', 'PROV', 'AGLOSI']",stats_H_Q-PROV-AGLOSI_sample0.02.csv,stats_M14_Q-PROV-AGLOSI_sample0.02.csv,stats_M24_Q-PROV-AGLOSI_sample0.02.csv,stats_P_Q-PROV-AGLOSI_sample0.02.csv
"['Q', 'PROV']",stats_H_Q-PROV_sample0.02.csv,stats_M14_Q-PROV_sample0.02.csv,stats_M24_Q-PROV_sample0.02.csv,stats_P_Q-PROV_sample0.02.csv
"['Q', 'Region', 'AGLOSI']",stats_H_Q-Region-AGLOSI_sample0.02.csv,stats_M14_Q-Region-AGLOSI_sample0.02.csv,stats_M24_Q-Region-AGLOSI_sample0.02.csv,stats_P_Q-Region-AGLOSI_sample0.02.csv
"['Q', 'Region']",stats_H_Q-Region_sample0.02.csv,stats_M14_Q-Region_sample0.02.csv,stats_M24_Q-Region_sample0.02.csv,stats_P_Q-Region_sample0.02.csv
"['Q', 'Total']",stats_H_Q-Total_sample0.02.csv,stats_M14_Q-Total_sample0.02.csv,stats_M24_Q-Total_sample0.02.csv,stats_P_Q-Total_sample0.02.csv

In [7]:
personas_ingresos_df = pd.DataFrame({
    'frac': [frac for frac in pobreza_fracs for _ in pobreza_quarters for _ in pobreza_experiment_tags],
    'quarter': [quarter for _ in pobreza_fracs for quarter in pobreza_quarters for _ in pobreza_experiment_tags],
    'experiment_tag': [tag for _ in pobreza_fracs for _ in pobreza_quarters for tag in pobreza_experiment_tags],
    'filename': personas_ingresos_filenames,
    'full_path': [f"{pobreza_path}{filename}" for filename in personas_ingresos_filenames]
})

In [8]:
personas_ingresos_df.set_index(['quarter', 'frac'])['filename'].unstack()[[0.02]]

frac                                                   0.02
quarter
2020-02-15  individual_income_sample0.02_2020-02-15_ARG.csv
2020-05-15  individual_income_sample0.02_2020-05-15_ARG.csv
2020-08-15  individual_income_sample0.02_2020-08-15_ARG.csv
2020-11-15  individual_income_sample0.02_2020-11-15_ARG.csv
2021-02-15  individual_income_sample0.02_2021-02-15_ARG.csv
2021-05-15  individual_income_sample0.02_2021-05-15_ARG.csv
2021-08-15  individual_income_sample0.02_2021-08-15_ARG.csv
2021-11-15  individual_income_sample0.02_2021-11-15_ARG.csv
2022-02-15  individual_income_sample0.02_2022-02-15_ARG.csv
2022-05-15  individual_income_sample0.02_2022-05-15_ARG.csv
2022-08-15  individual_income_sample0.02_2022-08-15_ARG.csv
2022-11-15  individual_income_sample0.02_2022-11-15_ARG.csv
2023-02-15  individual_income_sample0.02_2023-02-15_ARG.csv
2023-05-15  individual_income_sample0.02_2023-05-15_ARG.csv
2023-08-15  individual_income_sample0.02_2023-08-15_ARG.csv
2023-11-15  individual_income_sample0.02_2023-11-15_ARG.csv
2024-02-15  individual_income_sample0.02_2024-02-15_ARG.csv
2024-05-15  individual_income_sample0.02_2024-05-15_ARG.csv
2024-08-15  individual_income_sample0.02_2024-08-15_ARG.csv
2024-11-15  individual_income_sample0.02_2024-11-15_ARG.csv

In [9]:
pobreza_hogares_df = pd.DataFrame({
    'frac': [frac for frac in pobreza_fracs for _ in pobreza_quarters],
    'quarter': [quarter for _ in pobreza_fracs for quarter in pobreza_quarters],
    'filename': pobreza_hogares_filenames,
    'full_path': [f"{pobreza_path}{filename}" for filename in pobreza_hogares_filenames]
})

In [10]:
pobreza_hogares_df.set_index(['quarter', 'frac'])['filename'].unstack()[[0.02]]

frac                                                    0.02
quarter
2020-02-15  household_poverty_sample0.02_q2020-02-15_ARG.csv
2020-05-15  household_poverty_sample0.02_q2020-05-15_ARG.csv
2020-08-15  household_poverty_sample0.02_q2020-08-15_ARG.csv
2020-11-15  household_poverty_sample0.02_q2020-11-15_ARG.csv
2021-02-15  household_poverty_sample0.02_q2021-02-15_ARG.csv
2021-05-15  household_poverty_sample0.02_q2021-05-15_ARG.csv
2021-08-15  household_poverty_sample0.02_q2021-08-15_ARG.csv
2021-11-15  household_poverty_sample0.02_q2021-11-15_ARG.csv
2022-02-15  household_poverty_sample0.02_q2022-02-15_ARG.csv
2022-05-15  household_poverty_sample0.02_q2022-05-15_ARG.csv
2022-08-15  household_poverty_sample0.02_q2022-08-15_ARG.csv
2022-11-15  household_poverty_sample0.02_q2022-11-15_ARG.csv
2023-02-15  household_poverty_sample0.02_q2023-02-15_ARG.csv
2023-05-15  household_poverty_sample0.02_q2023-05-15_ARG.csv
2023-08-15  household_poverty_sample0.02_q2023-08-15_ARG.csv
2023-11-15  household_poverty_sample0.02_q2023-11-15_ARG.csv
2024-02-15  household_poverty_sample0.02_q2024-02-15_ARG.csv
2024-05-15  household_poverty_sample0.02_q2024-05-15_ARG.csv
2024-08-15  household_poverty_sample0.02_q2024-08-15_ARG.csv
2024-11-15  household_poverty_sample0.02_q2024-11-15_ARG.csv

In [11]:
hogares_geo_df = pd.DataFrame({
    'frac': [frac for frac in pobreza_fracs for _ in pobreza_years for _ in pobreza_experiment_tags],
    'year': [year for _ in pobreza_fracs for year in pobreza_years for _ in pobreza_experiment_tags],
    'experiment_tag': [tag for _ in pobreza_fracs for _ in pobreza_years for tag in pobreza_experiment_tags],
    'filename': hogares_geo_filenames,
    'full_path': [f"{pobreza_path}{filename}" for filename in hogares_geo_filenames]
})

hogares_geo_df.set_index(['year', 'frac'])['filename'].unstack()[[0.02]]

frac                                    0.02
year
2020  geo_households_sample0.02_2020_ARG.csv
2021  geo_households_sample0.02_2021_ARG.csv
2022  geo_households_sample0.02_2022_ARG.csv
2023  geo_households_sample0.02_2023_ARG.csv
2024  geo_households_sample0.02_2024_ARG.csv

In [12]:
geojson_df = pd.DataFrame({
    'method': [method for method in methods for _ in geo_levels for _ in pobreza_fracs],
    'geo_level': [geo_level for _ in methods for geo_level in geo_levels for _ in pobreza_fracs],
    'frac': [frac for _ in methods for _ in geo_levels for frac in pobreza_fracs],
    'filename': geojson_filenames,
    'full_path': [f"{geojson_path}{filename}" for filename in geojson_filenames]
})

In [13]:
geojson_df.loc[geojson_df.frac == 0.02].set_index(['method', 'geo_level'])['filename'].unstack()

geo_level,DPTO,IDFRAC,PROV
method,,,
H,pobreza_H_DPTO_sample0.02.geojson,pobreza_H_IDFRAC_sample0.02.geojson,pobreza_H_PROV_sample0.02.geojson
M14,pobreza_M14_DPTO_sample0.02.geojson,pobreza_M14_IDFRAC_sample0.02.geojson,pobreza_M14_PROV_sample0.02.geojson
M24,pobreza_M24_DPTO_sample0.02.geojson,pobreza_M24_IDFRAC_sample0.02.geojson,pobreza_M24_PROV_sample0.02.geojson
P,pobreza_P_DPTO_sample0.02.geojson,pobreza_P_IDFRAC_sample0.02.geojson,pobreza_P_PROV_sample0.02.geojson

In [14]:
# pd.read_csv('./../data/Pobreza/hogares_geo_f0.005_2015_ARG.csv')
# pd.read_csv('./../data/Pobreza/pobreza_hogares_f0.005_2015.csv')
# pd.read_csv('./../data/results/result_H_Q-AGLOMERADO_0.005.csv')
# pd.read_csv('./../data/Pobreza/personas_ingresos_f0.005_2018.csv')
# pd.read_csv('./../data/geojson/pobreza_H_PROV.geojson')

## Google Cloud

In [15]:
# from google.cloud import storage
# import pandas as pd
# import io

# # Initialize a client
# client = storage.Client()

# # The ID of your GCS bucket
# bucket_name = 'your-bucket-name'

# # The path to your file to upload
# destination_blob_name = 'your-file-name.csv'

# # Your pandas DataFrame
# df = pd.DataFrame({'col1': [1, 2], 'col2': [3, 4]})

# # Convert DataFrame to CSV
# csv_data = df.to_csv(index=False)

# # Upload the DataFrame
# bucket = client.bucket(bucket_name)
# blob = bucket.blob(destination_blob_name)
# blob.upload_from_string(csv_data, content_type='text/csv')
# print(f"File {destination_blob_name} uploaded to {bucket_name}.")

In [16]:
import pandas as pd

hogares_geo_df = pd.DataFrame({
    'frac': [frac for frac in pobreza_fracs for _ in pobreza_years for _ in pobreza_experiment_tags],
    'year': [year for _ in pobreza_fracs for year in pobreza_years for _ in pobreza_experiment_tags],
    'experiment_tag': [tag for _ in pobreza_fracs for _ in pobreza_years for tag in pobreza_experiment_tags],
    'filename': hogares_geo_filenames,
    'full_path': [f"{pobreza_path}{filename}" for filename in hogares_geo_filenames]
})

hogares_geo_df = hogares_geo_df.set_index(['year', 'frac'])['filename'].unstack()[[0.02]]
hogares_geo_df.head()

frac                                    0.02
year
2020  geo_households_sample0.02_2020_ARG.csv
2021  geo_households_sample0.02_2021_ARG.csv
2022  geo_households_sample0.02_2022_ARG.csv
2023  geo_households_sample0.02_2023_ARG.csv
2024  geo_households_sample0.02_2024_ARG.csv

In [17]:
import os
import subprocess

path = pobreza_path
filenames = hogares_geo_filenames

# Subir archivos a Google Cloud
os.system("gcloud config set project argentinian-poverty-atlas")
BUCKET_NAME = "argentinian-poverty-atlas-downloads"


# Loop through the filenames to upload
for filename in filenames:
    local_path = f"{path}{filename}"
    cloud_path = f"gs://{BUCKET_NAME}/{filename}"
    
    # Check if the file already exists in the cloud
    result = subprocess.run(['gsutil', '-q', 'stat', cloud_path], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if result.returncode == 0:
        print(f"File {filename} already exists in the bucket. Skipping upload.")
    else:
        print(f"Uploading {filename} to Google Cloud Storage.")
        os.system(f"gsutil cp {local_path} {cloud_path}")

WARNING: Your active project does not match the quota project in your local Application Default Credentials file. This might result in unexpected quota issues.

To update your Application Default Credentials quota project, use the `gcloud auth application-default set-quota-project` command.
WARNING: [matuteiglesias@gmail.com] does not have permission to access projects instance [argentinian-poverty-atlas] (or it may not exist): The caller does not have permission. This command is authenticated as matuteiglesias@gmail.com which is the active account specified by the [core/account] property
Updated property [core/project].

Uploading geo_households_sample0.01_2020_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/geo_households_sample0.01_2020_ARG.csv [Content-Type=text/csv]...
- [1 files][ 15.3 MiB/ 15.3 MiB]
Operation completed over 1 objects/15.3 MiB.

Uploading geo_households_sample0.01_2021_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/geo_households_sample0.01_2021_ARG.csv [Content-Type=text/csv]...
- [1 files][ 15.5 MiB/ 15.5 MiB]
Operation completed over 1 objects/15.5 MiB.

Uploading geo_households_sample0.01_2022_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/geo_households_sample0.01_2022_ARG.csv [Content-Type=text/csv]...
- [1 files][ 15.6 MiB/ 15.6 MiB]
Operation completed over 1 objects/15.6 MiB.

Uploading geo_households_sample0.01_2023_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/geo_households_sample0.01_2023_ARG.csv [Content-Type=text/csv]...
- [1 files][ 15.7 MiB/ 15.7 MiB]
Operation completed over 1 objects/15.7 MiB.

Uploading geo_households_sample0.01_2024_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/geo_households_sample0.01_2024_ARG.csv [Content-Type=text/csv]...
- [1 files][ 15.9 MiB/ 15.9 MiB]
Operation completed over 1 objects/15.9 MiB.

File geo_households_sample0.02_2020_ARG.csv already exists in the bucket. Skipping upload.
File geo_households_sample0.02_2021_ARG.csv already exists in the bucket. Skipping upload.
File geo_households_sample0.02_2022_ARG.csv already exists in the bucket. Skipping upload.
Uploading geo_households_sample0.02_2023_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/geo_households_sample0.02_2023_ARG.csv [Content-Type=text/csv]...
- [1 files][ 31.5 MiB/ 31.5 MiB]
Operation completed over 1 objects/31.5 MiB.

Uploading geo_households_sample0.02_2024_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/geo_households_sample0.02_2024_ARG.csv [Content-Type=text/csv]...
- [1 files][ 20.7 MiB/ 20.7 MiB]
Operation completed over 1 objects/20.7 MiB.

In [18]:
filenames = personas_ingresos_filenames

# Subir archivos a Google Cloud
os.system("gcloud config set project argentinian-poverty-atlas")
BUCKET_NAME = "argentinian-poverty-atlas-downloads"


# Loop through the filenames to upload
for filename in filenames:
    local_path = f"{path}{filename}"
    cloud_path = f"gs://{BUCKET_NAME}/{filename}"
    
    # Check if the file already exists in the cloud
    result = subprocess.run(['gsutil', '-q', 'stat', cloud_path], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if result.returncode == 0:
        print(f"File {filename} already exists in the bucket. Skipping upload.")
    else:
        print(f"Uploading {filename} to Google Cloud Storage.")
        os.system(f"gsutil cp {local_path} {cloud_path}")

WARNING: Your active project does not match the quota project in your local Application Default Credentials file. This might result in unexpected quota issues.

To update your Application Default Credentials quota project, use the `gcloud auth application-default set-quota-project` command.
WARNING: [matuteiglesias@gmail.com] does not have permission to access projects instance [argentinian-poverty-atlas] (or it may not exist): The caller does not have permission. This command is authenticated as matuteiglesias@gmail.com which is the active account specified by the [core/account] property
Updated property [core/project].

Uploading individual_income_sample0.01_2020-02-15_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/individual_income_sample0.01_2020-02-15_ARG.csv [Content-Type=text/csv]...
- [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.

Uploading individual_income_sample0.01_2020-05-15_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/individual_income_sample0.01_2020-05-15_ARG.csv [Content-Type=text/csv]...
- [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.

Uploading individual_income_sample0.01_2020-08-15_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/individual_income_sample0.01_2020-08-15_ARG.csv [Content-Type=text/csv]...
- [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.

Uploading individual_income_sample0.01_2020-11-15_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/individual_income_sample0.01_2020-11-15_ARG.csv [Content-Type=text/csv]...
- [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.

Uploading individual_income_sample0.01_2021-02-15_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/individual_income_sample0.01_2021-02-15_ARG.csv [Content-Type=text/csv]...
- [1 files][ 18.4 MiB/ 18.4 MiB]
Operation completed over 1 objects/18.4 MiB.

Uploading individual_income_sample0.01_2021-05-15_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/individual_income_sample0.01_2021-05-15_ARG.csv [Content-Type=text/csv]...
- [1 files][ 18.4 MiB/ 18.4 MiB]
Operation completed over 1 objects/18.4 MiB.

Uploading individual_income_sample0.01_2021-08-15_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/individual_income_sample0.01_2021-08-15_ARG.csv [Content-Type=text/csv]...
- [1 files][ 18.4 MiB/ 18.4 MiB]
Operation completed over 1 objects/18.4 MiB.

Uploading individual_income_sample0.01_2021-11-15_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/individual_income_sample0.01_2021-11-15_ARG.csv [Content-Type=text/csv]...
- [1 files][ 18.4 MiB/ 18.4 MiB]
Operation completed over 1 objects/18.4 MiB.

Uploading individual_income_sample0.01_2022-02-15_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/individual_income_sample0.01_2022-02-15_ARG.csv [Content-Type=text/csv]...
- [1 files][ 18.4 MiB/ 18.4 MiB]
Operation completed over 1 objects/18.4 MiB.

Uploading individual_income_sample0.01_2022-05-15_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/individual_income_sample0.01_2022-05-15_ARG.csv [Content-Type=text/csv]...
- [1 files][ 18.4 MiB/ 18.4 MiB]
Operation completed over 1 objects/18.4 MiB.

Uploading individual_income_sample0.01_2022-08-15_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/individual_income_sample0.01_2022-08-15_ARG.csv [Content-Type=text/csv]...
- [1 files][ 18.4 MiB/ 18.4 MiB]
Operation completed over 1 objects/18.4 MiB.

Uploading individual_income_sample0.01_2022-11-15_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/individual_income_sample0.01_2022-11-15_ARG.csv [Content-Type=text/csv]...
- [1 files][ 18.4 MiB/ 18.4 MiB]
Operation completed over 1 objects/18.4 MiB.

Uploading individual_income_sample0.01_2023-02-15_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/individual_income_sample0.01_2023-02-15_ARG.csv [Content-Type=text/csv]...
- [1 files][ 18.7 MiB/ 18.7 MiB]
Operation completed over 1 objects/18.7 MiB.

Uploading individual_income_sample0.01_2023-05-15_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/individual_income_sample0.01_2023-05-15_ARG.csv [Content-Type=text/csv]...
- [1 files][ 18.7 MiB/ 18.7 MiB]
Operation completed over 1 objects/18.7 MiB.

Uploading individual_income_sample0.01_2023-08-15_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/individual_income_sample0.01_2023-08-15_ARG.csv [Content-Type=text/csv]...
- [1 files][ 18.7 MiB/ 18.7 MiB]
Operation completed over 1 objects/18.7 MiB.

Uploading individual_income_sample0.01_2023-11-15_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/individual_income_sample0.01_2023-11-15_ARG.csv [Content-Type=text/csv]...
- [1 files][ 18.6 MiB/ 18.6 MiB]
Operation completed over 1 objects/18.6 MiB.

Uploading individual_income_sample0.01_2024-02-15_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/individual_income_sample0.01_2024-02-15_ARG.csv [Content-Type=text/csv]...
- [1 files][ 18.8 MiB/ 18.8 MiB]
Operation completed over 1 objects/18.8 MiB.

Uploading individual_income_sample0.01_2024-05-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/individual_income_sample0.01_2024-05-15_ARG.csv

Uploading individual_income_sample0.01_2024-08-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/individual_income_sample0.01_2024-08-15_ARG.csv

Uploading individual_income_sample0.01_2024-11-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/individual_income_sample0.01_2024-11-15_ARG.csv

File individual_income_sample0.02_2020-02-15_ARG.csv already exists in the bucket. Skipping upload.
File individual_income_sample0.02_2020-05-15_ARG.csv already exists in the bucket. Skipping upload.
File individual_income_sample0.02_2020-08-15_ARG.csv already exists in the bucket. Skipping upload.
File individual_income_sample0.02_2020-11-15_ARG.csv already exists in the bucket. Skipping upload.
File individual_income_sample0.02_2021-02-15_ARG.csv already exists in the bucket. Skipping upload.
File individual_income_sample0.02_2021-05-15_ARG.csv already exists in the bucket. Skipping upload.
File individual_income_sample0.02_2021-08-15_ARG.csv already exists in the bucket. Skipping upload.
File individual_income_sample0.02_2021-11-15_ARG.csv already exists in the bucket. Skipping upload.
File individual_income_sample0.02_2022-02-15_ARG.csv already exists in the bucket. Skipping upload.
File individual_income_sample0.02_2022-05-15_ARG.csv already exists in the bucket. Skipping upload.
File individual_income_sample0.02_2022-08-15_ARG.csv already exists in the bucket. Skipping upload.
File individual_income_sample0.02_2022-11-15_ARG.csv already exists in the bucket. Skipping upload.
Uploading individual_income_sample0.02_2023-02-15_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/individual_income_sample0.02_2023-02-15_ARG.csv [Content-Type=text/csv]...
\ [1 files][ 38.2 MiB/ 38.2 MiB]
Operation completed over 1 objects/38.2 MiB.

Uploading individual_income_sample0.02_2023-05-15_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/individual_income_sample0.02_2023-05-15_ARG.csv [Content-Type=text/csv]...
- [1 files][ 38.2 MiB/ 38.2 MiB]
Operation completed over 1 objects/38.2 MiB.

Uploading individual_income_sample0.02_2023-08-15_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/individual_income_sample0.02_2023-08-15_ARG.csv [Content-Type=text/csv]...
- [1 files][ 38.2 MiB/ 38.2 MiB]
Operation completed over 1 objects/38.2 MiB.

Uploading individual_income_sample0.02_2023-11-15_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/individual_income_sample0.02_2023-11-15_ARG.csv [Content-Type=text/csv]...
- [1 files][ 38.1 MiB/ 38.1 MiB]
Operation completed over 1 objects/38.1 MiB.

Uploading individual_income_sample0.02_2024-02-15_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/individual_income_sample0.02_2024-02-15_ARG.csv [Content-Type=text/csv]...
- [1 files][ 27.3 MiB/ 27.3 MiB]
Operation completed over 1 objects/27.3 MiB.

Uploading individual_income_sample0.02_2024-05-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/individual_income_sample0.02_2024-05-15_ARG.csv

Uploading individual_income_sample0.02_2024-08-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/individual_income_sample0.02_2024-08-15_ARG.csv

Uploading individual_income_sample0.02_2024-11-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/individual_income_sample0.02_2024-11-15_ARG.csv

In [19]:
filenames = pobreza_hogares_filenames

# Subir archivos a Google Cloud
os.system("gcloud config set project argentinian-poverty-atlas")
BUCKET_NAME = "argentinian-poverty-atlas-downloads"


# Loop through the filenames to upload
for filename in filenames:
    local_path = f"{path}{filename}"
    cloud_path = f"gs://{BUCKET_NAME}/{filename}"
    
    # Check if the file already exists in the cloud
    result = subprocess.run(['gsutil', '-q', 'stat', cloud_path], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if result.returncode == 0:
        print(f"File {filename} already exists in the bucket. Skipping upload.")
    else:
        print(f"Uploading {filename} to Google Cloud Storage.")
        os.system(f"gsutil cp {local_path} {cloud_path}")

WARNING: Your active project does not match the quota project in your local Application Default Credentials file. This might result in unexpected quota issues.

To update your Application Default Credentials quota project, use the `gcloud auth application-default set-quota-project` command.
WARNING: [matuteiglesias@gmail.com] does not have permission to access projects instance [argentinian-poverty-atlas] (or it may not exist): The caller does not have permission. This command is authenticated as matuteiglesias@gmail.com which is the active account specified by the [core/account] property
Updated property [core/project].

Uploading household_poverty_sample0.01_q2020-02-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/household_poverty_sample0.01_q2020-02-15_ARG.csv

Uploading household_poverty_sample0.01_q2020-05-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/household_poverty_sample0.01_q2020-05-15_ARG.csv

Uploading household_poverty_sample0.01_q2020-08-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/household_poverty_sample0.01_q2020-08-15_ARG.csv

Uploading household_poverty_sample0.01_q2020-11-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/household_poverty_sample0.01_q2020-11-15_ARG.csv

Uploading household_poverty_sample0.01_q2021-02-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/household_poverty_sample0.01_q2021-02-15_ARG.csv

Uploading household_poverty_sample0.01_q2021-05-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/household_poverty_sample0.01_q2021-05-15_ARG.csv

Uploading household_poverty_sample0.01_q2021-08-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/household_poverty_sample0.01_q2021-08-15_ARG.csv

Uploading household_poverty_sample0.01_q2021-11-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/household_poverty_sample0.01_q2021-11-15_ARG.csv

Uploading household_poverty_sample0.01_q2022-02-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/household_poverty_sample0.01_q2022-02-15_ARG.csv

Uploading household_poverty_sample0.01_q2022-05-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/household_poverty_sample0.01_q2022-05-15_ARG.csv

Uploading household_poverty_sample0.01_q2022-08-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/household_poverty_sample0.01_q2022-08-15_ARG.csv

Uploading household_poverty_sample0.01_q2022-11-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/household_poverty_sample0.01_q2022-11-15_ARG.csv

Uploading household_poverty_sample0.01_q2023-02-15_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/household_poverty_sample0.01_q2023-02-15_ARG.csv [Content-Type=text/csv]...
- [1 files][ 10.2 MiB/ 10.2 MiB]
Operation completed over 1 objects/10.2 MiB.

Uploading household_poverty_sample0.01_q2023-05-15_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/household_poverty_sample0.01_q2023-05-15_ARG.csv [Content-Type=text/csv]...
- [1 files][ 10.1 MiB/ 10.1 MiB]
Operation completed over 1 objects/10.1 MiB.

Uploading household_poverty_sample0.01_q2023-08-15_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/household_poverty_sample0.01_q2023-08-15_ARG.csv [Content-Type=text/csv]...
- [1 files][ 10.1 MiB/ 10.1 MiB]
Operation completed over 1 objects/10.1 MiB.

Uploading household_poverty_sample0.01_q2023-11-15_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/household_poverty_sample0.01_q2023-11-15_ARG.csv [Content-Type=text/csv]...
- [1 files][ 10.1 MiB/ 10.1 MiB]
Operation completed over 1 objects/10.1 MiB.

Uploading household_poverty_sample0.01_q2024-02-15_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/household_poverty_sample0.01_q2024-02-15_ARG.csv [Content-Type=text/csv]...
- [1 files][ 10.2 MiB/ 10.2 MiB]
Operation completed over 1 objects/10.2 MiB.

Uploading household_poverty_sample0.01_q2024-05-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/household_poverty_sample0.01_q2024-05-15_ARG.csv

Uploading household_poverty_sample0.01_q2024-08-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/household_poverty_sample0.01_q2024-08-15_ARG.csv

Uploading household_poverty_sample0.01_q2024-11-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/household_poverty_sample0.01_q2024-11-15_ARG.csv

Uploading household_poverty_sample0.02_q2020-02-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/household_poverty_sample0.02_q2020-02-15_ARG.csv

Uploading household_poverty_sample0.02_q2020-05-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/household_poverty_sample0.02_q2020-05-15_ARG.csv

Uploading household_poverty_sample0.02_q2020-08-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/household_poverty_sample0.02_q2020-08-15_ARG.csv

Uploading household_poverty_sample0.02_q2020-11-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/household_poverty_sample0.02_q2020-11-15_ARG.csv

Uploading household_poverty_sample0.02_q2021-02-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/household_poverty_sample0.02_q2021-02-15_ARG.csv

Uploading household_poverty_sample0.02_q2021-05-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/household_poverty_sample0.02_q2021-05-15_ARG.csv

Uploading household_poverty_sample0.02_q2021-08-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/household_poverty_sample0.02_q2021-08-15_ARG.csv

Uploading household_poverty_sample0.02_q2021-11-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/household_poverty_sample0.02_q2021-11-15_ARG.csv

Uploading household_poverty_sample0.02_q2022-02-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/household_poverty_sample0.02_q2022-02-15_ARG.csv

Uploading household_poverty_sample0.02_q2022-05-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/household_poverty_sample0.02_q2022-05-15_ARG.csv

Uploading household_poverty_sample0.02_q2022-08-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/household_poverty_sample0.02_q2022-08-15_ARG.csv

Uploading household_poverty_sample0.02_q2022-11-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/household_poverty_sample0.02_q2022-11-15_ARG.csv

Uploading household_poverty_sample0.02_q2023-02-15_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/household_poverty_sample0.02_q2023-02-15_ARG.csv [Content-Type=text/csv]...
- [1 files][ 20.3 MiB/ 20.3 MiB]
Operation completed over 1 objects/20.3 MiB.

Uploading household_poverty_sample0.02_q2023-05-15_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/household_poverty_sample0.02_q2023-05-15_ARG.csv [Content-Type=text/csv]...
- [1 files][ 20.3 MiB/ 20.3 MiB]
Operation completed over 1 objects/20.3 MiB.

Uploading household_poverty_sample0.02_q2023-08-15_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/household_poverty_sample0.02_q2023-08-15_ARG.csv [Content-Type=text/csv]...
- [1 files][ 20.3 MiB/ 20.3 MiB]
Operation completed over 1 objects/20.3 MiB.

Uploading household_poverty_sample0.02_q2023-11-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/household_poverty_sample0.02_q2023-11-15_ARG.csv

Uploading household_poverty_sample0.02_q2024-02-15_ARG.csv to Google Cloud Storage.

Copying file://./../data/Pobreza/household_poverty_sample0.02_q2024-02-15_ARG.csv [Content-Type=text/csv]...
- [1 files][ 12.9 MiB/ 12.9 MiB]
Operation completed over 1 objects/12.9 MiB.

Uploading household_poverty_sample0.02_q2024-05-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/household_poverty_sample0.02_q2024-05-15_ARG.csv

Uploading household_poverty_sample0.02_q2024-08-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/household_poverty_sample0.02_q2024-08-15_ARG.csv

Uploading household_poverty_sample0.02_q2024-11-15_ARG.csv to Google Cloud Storage.

CommandException: No URLs matched: ./../data/Pobreza/household_poverty_sample0.02_q2024-11-15_ARG.csv

In [21]:
import os
import subprocess
import glob

# Set the path to the results directory
results_path = './../data/results/'

# List all files in the results directory that match the pattern
filenames = glob.glob(f"{results_path}/stats_*sample0.02.csv")

# Set the Google Cloud project and bucket name
os.system("gcloud config set project argentinian-poverty-atlas")
BUCKET_NAME = "argentinian-poverty-atlas-downloads"

# Loop through the filenames to upload
for local_path in filenames:
    filename = os.path.basename(local_path)
    cloud_path = f"gs://{BUCKET_NAME}/{filename}"
    
    # # Check if the file already exists in the cloud
    # result = subprocess.run(['gsutil', '-q', 'stat', cloud_path], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    # if result.returncode == 0:
    #     print(f"File {filename} already exists in the bucket. Skipping upload.")
    # else:
    print(f"Uploading {filename} to Google Cloud Storage.")
    os.system(f"gsutil cp '{local_path}' '{cloud_path}'")

WARNING: Your active project does not match the quota project in your local Application Default Credentials file. This might result in unexpected quota issues.

To update your Application Default Credentials quota project, use the `gcloud auth application-default set-quota-project` command.
WARNING: [matuteiglesias@gmail.com] does not have permission to access projects instance [argentinian-poverty-atlas] (or it may not exist): The caller does not have permission. This command is authenticated as matuteiglesias@gmail.com which is the active account specified by the [core/account] property
Updated property [core/project].

Uploading stats_P_Q-DPTO_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_P_Q-DPTO_sample0.02.csv [Content-Type=text/csv]...
\ [1 files][ 77.5 MiB/ 77.5 MiB]
Operation completed over 1 objects/77.5 MiB.

Uploading stats_Hp_Q-AGLOMERADO_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_Hp_Q-AGLOMERADO_sample0.02.csv [Content-Type=text/csv]...
- [1 files][  3.7 MiB/  3.7 MiB]
Operation completed over 1 objects/3.7 MiB.

Uploading stats_Hi_Q-Total_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_Hi_Q-Total_sample0.02.csv [Content-Type=text/csv]...
/ [1 files][117.9 KiB/117.9 KiB]
Operation completed over 1 objects/117.9 KiB.

Uploading stats_Hp_Q-AGLOSI_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_Hp_Q-AGLOSI_sample0.02.csv [Content-Type=text/csv]...
/ [1 files][238.9 KiB/238.9 KiB]
Operation completed over 1 objects/238.9 KiB.

Uploading stats_P_Q-AGLOSI_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_P_Q-AGLOSI_sample0.02.csv [Content-Type=text/csv]...
/ [1 files][305.2 KiB/305.2 KiB]
Operation completed over 1 objects/305.2 KiB.

Uploading stats_PAGLO_Q-AGLOSI_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_PAGLO_Q-AGLOSI_sample0.02.csv [Content-Type=text/csv]...
/ [1 files][158.8 KiB/158.8 KiB]
Operation completed over 1 objects/158.8 KiB.

Uploading stats_Hi_Q-PROV-AGLOSI_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_Hi_Q-PROV-AGLOSI_sample0.02.csv [Content-Type=text/csv]...
- [1 files][  5.7 MiB/  5.7 MiB]
Operation completed over 1 objects/5.7 MiB.

Uploading stats_Hp_Q-PROV-AGLOSI_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_Hp_Q-PROV-AGLOSI_sample0.02.csv [Content-Type=text/csv]...
- [1 files][  5.7 MiB/  5.7 MiB]
Operation completed over 1 objects/5.7 MiB.

Uploading stats_M24_Q-AGLOSI_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_M24_Q-AGLOSI_sample0.02.csv [Content-Type=text/csv]...
/ [1 files][312.3 KiB/312.3 KiB]
Operation completed over 1 objects/312.3 KiB.

Uploading stats_Hi_Q-PROV_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_Hi_Q-PROV_sample0.02.csv [Content-Type=text/csv]...
/ [1 files][  2.7 MiB/  2.7 MiB]
Operation completed over 1 objects/2.7 MiB.

Uploading stats_H_Q-AGLOMERADO_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_H_Q-AGLOMERADO_sample0.02.csv [Content-Type=text/csv]...
- [1 files][  3.6 MiB/  3.6 MiB]
Operation completed over 1 objects/3.6 MiB.

Uploading stats_Hp_Q-PROV_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_Hp_Q-PROV_sample0.02.csv [Content-Type=text/csv]...
- [1 files][  2.7 MiB/  2.7 MiB]
Operation completed over 1 objects/2.7 MiB.

Uploading stats_Hi_Q-AGLOSI_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_Hi_Q-AGLOSI_sample0.02.csv [Content-Type=text/csv]...
/ [1 files][237.3 KiB/237.3 KiB]
Operation completed over 1 objects/237.3 KiB.

Uploading stats_P_Q-PROV_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_P_Q-PROV_sample0.02.csv [Content-Type=text/csv]...
- [1 files][  3.4 MiB/  3.4 MiB]
Operation completed over 1 objects/3.4 MiB.

Uploading stats_P_Q-Region-AGLOSI_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_P_Q-Region-AGLOSI_sample0.02.csv [Content-Type=text/csv]...
- [1 files][  2.0 MiB/  2.0 MiB]
Operation completed over 1 objects/2.0 MiB.

Uploading stats_Hi_Q-AGLOMERADO_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_Hi_Q-AGLOMERADO_sample0.02.csv [Content-Type=text/csv]...
- [1 files][  3.7 MiB/  3.7 MiB]
Operation completed over 1 objects/3.7 MiB.

Uploading stats_M24_Q-DPTO_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_M24_Q-DPTO_sample0.02.csv [Content-Type=text/csv]...
\ [1 files][ 79.8 MiB/ 79.8 MiB]
Operation completed over 1 objects/79.8 MiB.

Uploading stats_Hi_Q-Region_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_Hi_Q-Region_sample0.02.csv [Content-Type=text/csv]...
/ [1 files][753.1 KiB/753.1 KiB]
Operation completed over 1 objects/753.1 KiB.

Uploading stats_H_Q-Region-AGLOSI_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_H_Q-Region-AGLOSI_sample0.02.csv [Content-Type=text/csv]...
/ [1 files][  1.6 MiB/  1.6 MiB]
Operation completed over 1 objects/1.6 MiB.

Uploading stats_P_Q-PROV-AGLOSI_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_P_Q-PROV-AGLOSI_sample0.02.csv [Content-Type=text/csv]...
- [1 files][  7.4 MiB/  7.4 MiB]
Operation completed over 1 objects/7.4 MiB.

Uploading stats_P_Q-Total_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_P_Q-Total_sample0.02.csv [Content-Type=text/csv]...
/ [1 files][151.6 KiB/151.6 KiB]
Operation completed over 1 objects/151.6 KiB.

Uploading stats_PAGLO_Q-Region-AGLOSI_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_PAGLO_Q-Region-AGLOSI_sample0.02.csv [Content-Type=text/csv]...
/ [1 files][  1.0 MiB/  1.0 MiB]
Operation completed over 1 objects/1.0 MiB.

Uploading stats_M24_Q-P0910_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_M24_Q-P0910_sample0.02.csv [Content-Type=text/csv]...
/ [1 files][  2.2 MiB/  2.2 MiB]
Operation completed over 1 objects/2.2 MiB.

Uploading stats_M24_Q-Total_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_M24_Q-Total_sample0.02.csv [Content-Type=text/csv]...
/ [1 files][155.1 KiB/155.1 KiB]
Operation completed over 1 objects/155.1 KiB.

Uploading stats_Hp_Q-Region-AGLOSI_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_Hp_Q-Region-AGLOSI_sample0.02.csv [Content-Type=text/csv]...
/ [1 files][  1.6 MiB/  1.6 MiB]
Operation completed over 1 objects/1.6 MiB.

Uploading stats_Hp_Q-Total_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_Hp_Q-Total_sample0.02.csv [Content-Type=text/csv]...
/ [1 files][118.7 KiB/118.7 KiB]
Operation completed over 1 objects/118.7 KiB.

Uploading stats_H_Q-Region_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_H_Q-Region_sample0.02.csv [Content-Type=text/csv]...
/ [1 files][750.5 KiB/750.5 KiB]
Operation completed over 1 objects/750.5 KiB.

Uploading stats_PAGLO_Q-P0910_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_PAGLO_Q-P0910_sample0.02.csv [Content-Type=text/csv]...
/ [1 files][  2.3 MiB/  2.3 MiB]
Operation completed over 1 objects/2.3 MiB.

Uploading stats_PAGLO_Q-PROV_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_PAGLO_Q-PROV_sample0.02.csv [Content-Type=text/csv]...
- [1 files][  3.6 MiB/  3.6 MiB]
Operation completed over 1 objects/3.6 MiB.

Uploading stats_H_Q-PROV-AGLOSI_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_H_Q-PROV-AGLOSI_sample0.02.csv [Content-Type=text/csv]...
- [1 files][  5.7 MiB/  5.7 MiB]
Operation completed over 1 objects/5.7 MiB.

Uploading stats_PAGLO_Q-Region_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_PAGLO_Q-Region_sample0.02.csv [Content-Type=text/csv]...
/ [1 files][ 1010 KiB/ 1010 KiB]
Operation completed over 1 objects/1010.7 KiB.

Uploading stats_H_Q-DPTO_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_H_Q-DPTO_sample0.02.csv [Content-Type=text/csv]...
\ [1 files][ 60.4 MiB/ 60.4 MiB]
Operation completed over 1 objects/60.4 MiB.

Uploading stats_PAGLO_Q-PROV-AGLOSI_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_PAGLO_Q-PROV-AGLOSI_sample0.02.csv [Content-Type=text/csv]...
- [1 files][  3.8 MiB/  3.8 MiB]
Operation completed over 1 objects/3.8 MiB.

Uploading stats_M24_Q-PROV_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_M24_Q-PROV_sample0.02.csv [Content-Type=text/csv]...
- [1 files][  3.5 MiB/  3.5 MiB]
Operation completed over 1 objects/3.5 MiB.

Uploading stats_P_Q-Region_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_P_Q-Region_sample0.02.csv [Content-Type=text/csv]...
/ [1 files][967.8 KiB/967.8 KiB]
Operation completed over 1 objects/967.8 KiB.

Uploading stats_M24_Q-AGLOMERADO_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_M24_Q-AGLOMERADO_sample0.02.csv [Content-Type=text/csv]...
- [1 files][  4.8 MiB/  4.8 MiB]
Operation completed over 1 objects/4.8 MiB.

Uploading stats_Hi_Q-Region-AGLOSI_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_Hi_Q-Region-AGLOSI_sample0.02.csv [Content-Type=text/csv]...
- [1 files][  1.6 MiB/  1.6 MiB]
Operation completed over 1 objects/1.6 MiB.

Uploading stats_M24_Q-PROV-AGLOSI_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_M24_Q-PROV-AGLOSI_sample0.02.csv [Content-Type=text/csv]...
- [1 files][  7.6 MiB/  7.6 MiB]
Operation completed over 1 objects/7.6 MiB.

Uploading stats_Hp_Q-DPTO_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_Hp_Q-DPTO_sample0.02.csv [Content-Type=text/csv]...
\ [1 files][ 60.9 MiB/ 60.9 MiB]
Operation completed over 1 objects/60.9 MiB.

Uploading stats_H_Q-PROV_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_H_Q-PROV_sample0.02.csv [Content-Type=text/csv]...
/ [1 files][  2.7 MiB/  2.7 MiB]
Operation completed over 1 objects/2.7 MiB.

Uploading stats_M24_Q-Region_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_M24_Q-Region_sample0.02.csv [Content-Type=text/csv]...
/ [1 files][988.4 KiB/988.4 KiB]
Operation completed over 1 objects/988.4 KiB.

Uploading stats_M24_Q-Region-AGLOSI_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_M24_Q-Region-AGLOSI_sample0.02.csv [Content-Type=text/csv]...
- [1 files][  2.1 MiB/  2.1 MiB]
Operation completed over 1 objects/2.1 MiB.

Uploading stats_Hi_Q-DPTO_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_Hi_Q-DPTO_sample0.02.csv [Content-Type=text/csv]...
\ [1 files][ 59.1 MiB/ 59.1 MiB]
Operation completed over 1 objects/59.1 MiB.

Uploading stats_PAGLO_Q-Total_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_PAGLO_Q-Total_sample0.02.csv [Content-Type=text/csv]...
/ [1 files][158.8 KiB/158.8 KiB]
Operation completed over 1 objects/158.8 KiB.

Uploading stats_P_Q-P0910_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_P_Q-P0910_sample0.02.csv [Content-Type=text/csv]...
- [1 files][  2.1 MiB/  2.1 MiB]
Operation completed over 1 objects/2.1 MiB.

Uploading stats_Hp_Q-Region_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_Hp_Q-Region_sample0.02.csv [Content-Type=text/csv]...
- [1 files][757.4 KiB/757.4 KiB]
Operation completed over 1 objects/757.4 KiB.

Uploading stats_PAGLO_Q-AGLOMERADO_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_PAGLO_Q-AGLOMERADO_sample0.02.csv [Content-Type=text/csv]...
- [1 files][  4.8 MiB/  4.8 MiB]
Operation completed over 1 objects/4.8 MiB.

Uploading stats_PAGLO_Q-DPTO_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_PAGLO_Q-DPTO_sample0.02.csv [Content-Type=text/csv]...
- [1 files][ 16.2 MiB/ 16.2 MiB]
Operation completed over 1 objects/16.2 MiB.

Uploading stats_H_Q-Total_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_H_Q-Total_sample0.02.csv [Content-Type=text/csv]...
/ [1 files][117.6 KiB/117.6 KiB]
Operation completed over 1 objects/117.6 KiB.

Uploading stats_H_Q-AGLOSI_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_H_Q-AGLOSI_sample0.02.csv [Content-Type=text/csv]...
/ [1 files][236.4 KiB/236.4 KiB]
Operation completed over 1 objects/236.4 KiB.

Uploading stats_P_Q-AGLOMERADO_sample0.02.csv to Google Cloud Storage.

Copying file://./../data/results/stats_P_Q-AGLOMERADO_sample0.02.csv [Content-Type=text/csv]...
- [1 files][  4.7 MiB/  4.7 MiB]
Operation completed over 1 objects/4.7 MiB.

In [ ]:
xx

NameError: name 'xx' is not defined

In [ ]:
df = hogares_geo_df

# Generar tabla en HTML
html_table = df.to_html()
with open("tabla_results.html", "w") as f:
    f.write(html_table)

In [ ]:
cloud_path

'gs://argentinian-poverty-atlas-downloads//geo_households_sample0.02_2019_ARG.csv'

In [ ]:
pd.read_csv('./../data/Pobreza/geo_households_sample0.02_2016_ARG.csv')